services:
  # --- SHARED DATABASE ---
  mysqldb:
    image: mysql:8.0
    container_name: leadsphere-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=usersdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- DISCOVERY SERVER ---
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- API GATEWAY ---
  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy

  # --- JWT AUTH SERVICE ---
  jwt-auth-service:
    build: ./JWT-Auth-Service
    container_name: jwt-auth-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/usersdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      mysqldb:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # --- USER SERVICE ---
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/usersdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      mysqldb:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # --- LEAD SERVICE ---
  lead-service:
    build: ./lead-service
    container_name: lead-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/usersdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      mysqldb:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  # --- ANALYTICS SERVICE ---
  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy

networks:
  default:
    name: leadsphere-network