# --- IDENTITY ---
spring.application.name=lead-service

# --- DEFAULT ACTIVE PROFILE ---
spring.profiles.active=dev

# --- SHARED INFRASTRUCTURE ---
# Eureka discovery settings
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- COMMON SECURITY LOGGING ---
# Keep these here if you always want to see security logs in every environment
logging.level.org.springframework.security=DEBUG