#spring.application.name=api-gateway
#spring.profiles.active=dev
#
## Eureka Configuration (Shared)
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#
#management.endpoint.health.show-details=always
## Ensure endpoints are still accessible
#management.endpoints.web.exposure.include=health,info
#
## Disable specialized security for actuator to prevent bean conflict
#management.security.enabled=false
#
## This tells Spring Boot not to worry if a full security context isn't found for Actuator
#spring.main.allow-bean-definition-overriding=true


####################################################################
## --- IDENTITY ---
spring.application.name=api-gateway

## --- INFRASTRUCTURE ---
# This stays here but uses placeholders to be dynamic
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## --- MONITORING ---
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

## --- BEAN CONFLICT PREVENTION ---
spring.main.allow-bean-definition-overriding=true