#server.port=80
## Minimal logging for performance
#logging.level.org.springframework.web=ERROR


##############################################
server.port=${PORT:80}

## --- PROD INFRASTRUCTURE ---
eureka.client.service-url.defaultZone=${EUREKA_URL}

## --- PROD LOGGING ---
logging.level.org.springframework.web=ERROR

## --- SECURITY ---
# Reference production auth server
auth.server.url=${AUTH_SERVER_URL}