# --- IDENTITY ---
spring.application.name=User-Service

# --- DEFAULT ACTIVE PROFILE ---
# This ensures that if you just click "Run", it defaults to dev.
spring.profiles.active=dev

# --- SHARED INFRASTRUCTURE ---
# Eureka stays the same for most local/internal dev environments
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- FILE HANDLING ---
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB