
#####################################################################################
server.port=${PORT:8080}

## --- DATABASE (SECURE) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## --- JPA SETTINGS ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

## --- GMAIL SMTP (SECURE) ---
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.debug=false

## --- CLOUDINARY (SECURE) ---
cloudinary.cloud_name=${PROD_CLOUDINARY_NAME}
cloudinary.api_key=${PROD_CLOUDINARY_KEY}
cloudinary.api_secret=${PROD_CLOUDINARY_SECRET}