#server.port=8081
#
## MySQL Local Connection
##spring.datasource.url=jdbc:mysql://localhost:3306/usersdb
#spring.datasource.url=jdbc:mysql://mysqldb:3306/usersdb
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA + Hibernate (Aggressive logging for Dev)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## Gmail SMTP (Dev/Debug mode)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=v.rathore@braininventory.com
#spring.mail.password=vdlvxahgjdhawttt
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.debug=true
#
## Cloudinary (Dev account)
#cloudinary.cloud_name=dnpmn8agl
#cloudinary.api_key=495935492247926
#cloudinary.api_secret=q5aCjnudT0Svb7Hqu1M9t8AW8m4





#########################################################################
server.port=8081

## --- JPA + HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## --- GMAIL SMTP (DEV) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=v.rathore@braininventory.com
spring.mail.password=vdlvxahgjdhawttt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

## --- CLOUDINARY (DEV) ---
cloudinary.cloud_name=dnpmn8agl
cloudinary.api_key=495935492247926
cloudinary.api_secret=q5aCjnudT0Svb7Hqu1M9t8AW8m4

# Stability for Docker internal networking
eureka.instance.prefer-ip-address=${USE_IP:false}