#server.port=8761
#
## Disable peer registration and fetching
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
## Point the defaultZone back to itself
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## CRITICAL: This stops Eureka from looking for other nodes
#eureka.instance.hostname=localhost


###########################################################

server.port=8761

## --- DISCOVERY SETTINGS ---
# Eureka doesn't need to register with itself in a single-node setup
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

## --- DYNAMIC NETWORKING ---
# IDE Flow: EUREKA_HOST is not found -> uses 'localhost'
# Docker Flow: EUREKA_HOST is set to 'eureka-server' in compose -> uses 'eureka-server'
eureka.instance.hostname=${EUREKA_HOST:localhost}

# This uses the hostname resolved above
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/

# Recommended for Docker stability
eureka.instance.prefer-ip-address=${USE_IP:false}

