#spring.application.name=eureka-server
#spring.profiles.active=dev
#
## Common server settings
#eureka.server.eviction-interval-timer-in-ms=60000
#eureka.server.enable-self-preservation=true
#
#
#management.endpoint.health.show-details=always
#management.endpoints.web.exposure.include=health

###################################################################
## --- IDENTITY ---
spring.application.name=eureka-server

## --- COMMON SERVER SETTINGS ---
# How often to check for "dead" services (60 seconds)
eureka.server.eviction-interval-timer-in-ms=60000
# Prevents Eureka from clearing registry during network glitches
eureka.server.enable-self-preservation=true

## --- MONITORING ---
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health