#server.port=${EUREKA_PORT:8761}
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## The ':' provides a fallback so the URI parser doesn't crash on '${...}'
#eureka.client.service-url.defaultZone=${EUREKA_PEER_URL:http://localhost:8761/eureka/}




########################################################
server.port=${EUREKA_PORT:8761}

## --- CLUSTER SETTINGS ---
# In Prod, Eureka nodes usually synchronize with each other
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fallback URI ensures the app starts even if the environment variable is missing
eureka.client.service-url.defaultZone=${EUREKA_PEER_URL:http://localhost:8761/eureka/}