server.port=8085

# Local Resource Server Security (Local Auth Server)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/auth/realms/myrealm/protocol/openid-connect/certs

# Logging for local analysis development
logging.level.org.springframework.web=DEBUG