#server.port=8085
#
## Local Resource Server Security (Local Auth Server)
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/auth/realms/myrealm/protocol/openid-connect/certs
#
## Logging for local analysis development
#logging.level.org.springframework.web=DEBUG


#############################################################
# Port for local dev
server.port=8085

## --- LOGGING ---
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Recommended: Ensure container networking stability
eureka.instance.prefer-ip-address=${USE_IP:false}