
###############################
server.port=${PORT:8080}

## --- PRODUCTION INFRASTRUCTURE ---
eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## --- SECURITY ---
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_URL}/certs

## --- PERFORMANCE ---
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework.web=ERROR
logging.level.root=WARN