name: Inventotrack Multi-Arch CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Images
        run: |
          declare -A SERVICES
          SERVICES=( 
            ["analytics-service"]="analytics-service" 
            ["eureka-server"]="eureka-server" 
            ["Gateway"]="gateway" 
            ["JWT-Auth-Service"]="jwt_auth_service" 
            ["lead-service"]="lead-service" 
            ["user-service"]="user-service" 
          )
          
          for FOLDER in "${!SERVICES[@]}"; do
            IMAGE_NAME=${SERVICES[$FOLDER]}
            echo "--- Building $IMAGE_NAME ---"
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest \
              ./$FOLDER --push
          done

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/inventotrack/backend"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/inventotrack/backend
            docker-compose pull
            docker-compose up -d
            docker image prune -f