# --- IDENTITY ---
spring.application.name=JWT-Auth-Service

# --- DEFAULT ACTIVE PROFILE ---
spring.profiles.active=dev

# --- SHARED INFRASTRUCTURE ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- FEIGN CONFIGURATION ---
feign.okhttp.enabled=true

# --- SWAGGER/OPENAPI ---
springdoc.api-docs.path=/v3/api-docs